backend:
  name: git-gateway
  branch: master # or master, depending on your setup

media_folder: "static/images"
public_folder: "/images"

collections:
  # Your existing blog collection (check your current config for exact path)
  - name: "blog"
    label: "Blog"
    folder: "content/blog"  # Use the same path as your existing blog collection
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # New speakers collection
  - name: "speakers"
    label: "Speakers"
    folder: "content/speakers"  # Should match the same structure as your blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title/Position", name: "title", widget: "string" }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Speaker Image", name: "image", widget: "image" }
      - { label: "Talk Title", name: "talk_title", widget: "string" }
      - { label: "Talk Description", name: "talk_description", widget: "text" }
      - { label: "Featured Speaker", name: "featured", widget: "boolean", default: false }
      - { label: "Display Order", name: "order", widget: "number", default: 999, required: false }
      - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitter", widget: "string", required: false }
      - { label: "Website URL", name: "website", widget: "string", required: false }
      - { label: "Bio", name: "body", widget: "markdown" }